#ifndef NET_ERROR_H
#define NET_ERROR_H
#include <errno.h>
#include <netdb.h>
#include <openssl/err.h>
#include <openssl/ssl.h>

namespace net
{
	enum class NetError : long
	{
		// --- No Error
		ERR_OK = 0,

		// --- Self Define Error
		ERR_NET_URL_INVALID = 37,
		ERR_NET_PORT_INVALID = 41,

		// --- POSIX errno (common ones, add more as needed) ---
		ERR_EPERM = EPERM,
		ERR_ENOENT = ENOENT,
		ERR_ESRCH = ESRCH,
		ERR_EINTR = EINTR,
		ERR_EIO = EIO,
		ERR_ENXIO = ENXIO,
		ERR_E2BIG = E2BIG,
		ERR_ENOEXEC = ENOEXEC,
		ERR_EBADF = EBADF,
		ERR_ECHILD = ECHILD,
		ERR_EAGAIN = EAGAIN,
		ERR_ENOMEM = ENOMEM,
		ERR_EACCES = EACCES,
		ERR_EFAULT = EFAULT,
		ERR_ENOTBLK = ENOTBLK,
		ERR_EBUSY = EBUSY,
		ERR_EEXIST = EEXIST,
		ERR_EXDEV = EXDEV,
		ERR_ENODEV = ENODEV,
		ERR_ENOTDIR = ENOTDIR,
		ERR_EISDIR = EISDIR,
		ERR_EINVAL = EINVAL,
		ERR_ENFILE = ENFILE,
		ERR_EMFILE = EMFILE,
		ERR_ENOTTY = ENOTTY,
		ERR_ETXTBSY = ETXTBSY,
		ERR_EFBIG = EFBIG,
		ERR_ENOSPC = ENOSPC,
		ERR_ESPIPE = ESPIPE,
		ERR_EROFS = EROFS,
		ERR_EMLINK = EMLINK,
		ERR_EPIPE = EPIPE,
		ERR_EDOM = EDOM,
		ERR_ERANGE = ERANGE,

		// Common network/socket errno (some you listed):
		ERR_ECONNABORTED = ECONNABORTED,
		ERR_ECONNRESET = ECONNRESET,
		ERR_ENOBUFS = ENOBUFS,
		ERR_EISCONN = EISCONN,
		ERR_ENOTCONN = ENOTCONN,
		ERR_ESHUTDOWN = ESHUTDOWN,
		ERR_ETOOMANYREFS = ETOOMANYREFS,
		ERR_ETIMEDOUT = ETIMEDOUT,
		ERR_ECONNREFUSED = ECONNREFUSED,
		ERR_EHOSTDOWN = EHOSTDOWN,
		ERR_EHOSTUNREACH = EHOSTUNREACH,
		ERR_EALREADY = EALREADY,
		ERR_EINPROGRESS = EINPROGRESS,
		ERR_ESTALE = ESTALE,
		ERR_EUCLEAN = EUCLEAN,
		ERR_ENOTNAM = ENOTNAM,
		ERR_ENAVAIL = ENAVAIL,
		ERR_EISNAM = EISNAM,
		ERR_EREMOTEIO = EREMOTEIO,
		ERR_EDQUOT = EDQUOT,

		// --- OpenSSL SSL_get_error() return codes ---
		ERR_SSL_ERROR_NONE = SSL_ERROR_NONE,
		ERR_SSL_ERROR_SSL = SSL_ERROR_SSL,
		ERR_SSL_ERROR_WANT_READ = SSL_ERROR_WANT_READ,
		ERR_SSL_ERROR_WANT_WRITE = SSL_ERROR_WANT_WRITE,
		ERR_SSL_ERROR_WANT_X509_LOOKUP = SSL_ERROR_WANT_X509_LOOKUP,
		ERR_SSL_ERROR_SYSCALL = SSL_ERROR_SYSCALL,
		ERR_SSL_ERROR_ZERO_RETURN = SSL_ERROR_ZERO_RETURN,

		// --- OpenSSL ERR_get_error() reason codes (partial, most common) ---
		ERR_SSL_R_CERTIFICATE_VERIFY_FAILED = SSL_R_CERTIFICATE_VERIFY_FAILED,
		ERR_PEM_R_BAD_DECRYPT = PEM_R_BAD_DECRYPT,
		ERR_SSL3_CC_HANDSHAKE = SSL3_CC_HANDSHAKE,
		ERR_SSL_R_UNEXPECTED_MESSAGE = SSL_R_UNEXPECTED_MESSAGE,
		ERR_SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE =
		    SSL_R_PEER_DID_NOT_RETURN_A_CERTIFICATE,
		ERR_SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN =
		    SSL_R_SSLV3_ALERT_CERTIFICATE_UNKNOWN,

		// --- getaddrinfo() error codes ---
		ERR_EAI_AGAIN = EAI_AGAIN,
		ERR_EAI_BADFLAGS = EAI_BADFLAGS,
		ERR_EAI_FAIL = EAI_FAIL,
		ERR_EAI_FAMILY = EAI_FAMILY,
		ERR_EAI_MEMORY = EAI_MEMORY,
		ERR_EAI_NONAME = EAI_NONAME,
		ERR_EAI_SERVICE = EAI_SERVICE,
		ERR_EAI_SOCKTYPE = EAI_SOCKTYPE,
		ERR_EAI_SYSTEM = EAI_SYSTEM

	};
}
#endif // NET_ERROR_H
